# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
#markdown: rdiscount
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  rss_path: /atom.xml

production_url : http://seita.me # or your custom domain name
title : Seita


author :
  name : Seita
  email : seita.aka.guzi@gmail.com
  github : SeitaAkaGuzi
  twitter : seitazen
  feedbuder : seitazen

exclude: .rbenv-version
